[project]
name = ""
version = ""
description = ""
authors = [
    {name = "Brian Staszewski", email = "bstaz@users.noreply.github.com"},
]
dependencies = [
    "rich>=13.7.0",
    "rich-click>=1.7.2",
]
requires-python = ">=3.12"
readme = "README.md"
license = {text = "None"}

